// GENERATED by scripts/embed-offsets.mjs — do not edit by hand.
//
// The floor. When the mirror is unreachable — DNS failure, a 404, an empty cache — the
// client reads this instead of refusing to start, and says so rather than falling back
// silently. It is validated on load like any other bundle, because a build that shipped a
// malformed floor should fail its own tests rather than its users.
//
// Game build: V2026.8.18
// Source file: V2026.8.18/offsets.json
// Regenerate with: node scripts/embed-offsets.mjs

import type { IOffsets, IOffsetsLookup } from './offsetStore';

/** The build this floor describes, for the message the client shows when it is in use. */
export const EMBEDDED_GAME_VERSION = 'V2026.8.18';

/** The offsets file the embedded lookup's default entry names. */
export const EMBEDDED_OFFSETS_FILE = 'V2026.8.18/offsets.json';

export const EMBEDDED_LOOKUP: IOffsetsLookup = {
	patterns: {
		x64: {
			broadcastVersion: {
				sig: '33 D2 B9 ? ? ? ? 48 83 C4 ? E9 ? ? ? ?',
				patternOffset: 3,
				addressOffset: 0,
			},
		},
		x86: {
			broadcastVersion: {
				sig: '6A 00 68 ? ? ? ? E8 ? ? ? ? 83 C4 08 C3',
				patternOffset: 3,
				addressOffset: 0,
			},
		},
	},
	versions: {
		'50545250': {
			version: 'V2021.11.9',
			file: 'V2021.11.9/offsets.json',
			offsetsVersion: 26,
		},
		'50547300': {
			version: 'V2021.12.14',
			file: 'V2021.12.14/offsets.json',
			offsetsVersion: 26,
		},
		'50552300': {
			version: 'V2022.2.23',
			file: 'V2021.12.14/offsets.json',
			offsetsVersion: 26,
		},
		'50553700': {
			version: 'V2022.3.29',
			file: 'V2022.3.29/offsets.json',
			offsetsVersion: 26,
		},
		'50558200': {
			version: 'V2022.6.21',
			file: 'V2022.6.21/offsets.json',
			offsetsVersion: 26,
		},
		'50559600': {
			version: 'V2022.8.23',
			file: 'V2022.8.23/offsets.json',
			offsetsVersion: 26,
		},
		'50563850': {
			version: 'V2022.10.18',
			file: 'V2022.10.18/offsets.json',
			offsetsVersion: 26,
		},
		'50566300': {
			version: 'V2022.10.25',
			file: 'V2022.10.18/offsets.json',
			offsetsVersion: 26,
		},
		'50568050': {
			version: 'V2022.12.8',
			file: 'V2022.12.8/offsets.json',
			offsetsVersion: 26,
		},
		'50569850': {
			version: 'V2022.12.8',
			file: 'V2022.12.8/offsets.json',
			offsetsVersion: 26,
		},
		'50570250': {
			version: 'V2022.12.14',
			file: 'V2022.12.8/offsets.json',
			offsetsVersion: 26,
		},
		'50571700': {
			version: 'V2023.2.28',
			file: 'V2023.2.28/offsets.json',
			offsetsVersion: 26,
		},
		'50577350': {
			version: 'V2023.3.28',
			file: 'V2023.3.28/offsets.json',
			offsetsVersion: 26,
		},
		'50583250': {
			version: 'V2023.6.13',
			file: 'V2023.6.13/offsets.json',
			offsetsVersion: 26,
		},
		'50585000': {
			version: 'V2023.7.11',
			file: 'V2023.7.11/offsets.json',
			offsetsVersion: 26,
		},
		'50593050': {
			version: 'V2023.10.24',
			file: 'V2023.10.24/offsets.json',
			offsetsVersion: 26,
		},
		'50595550': {
			version: 'V2023.11.28',
			file: 'V2023.10.24/offsets.json',
			offsetsVersion: 26,
		},
		'50603650': {
			version: 'V2024.3.5',
			file: 'V2023.10.24/offsets.json',
			offsetsVersion: 15,
		},
		'50603750': {
			version: 'V2024.6.4',
			file: 'V2023.10.24/offsets.json',
			offsetsVersion: 15,
		},
		'50605450': {
			version: 'V2024.6.18',
			file: 'V2024.6.18/offsets.json',
			offsetsVersion: 15,
		},
		'50607250': {
			version: 'V2024.8.13',
			file: 'V2024.8.13/offsets.json',
			offsetsVersion: 15,
		},
		'50607300': {
			version: 'V2024.9.4',
			file: 'V2024.8.13/offsets.json',
			offsetsVersion: 15,
		},
		'50614900': {
			version: 'V2024.11.26',
			file: 'V2024.8.13/offsets.json',
			offsetsVersion: 15,
		},
		'50614950': {
			version: 'V2025.3.25',
			file: 'V2024.8.13/offsets.json',
			offsetsVersion: 15,
		},
		'50632950': {
			version: 'V2025.5.20',
			file: 'V2025.5.20/offsets.json',
			offsetsVersion: 6,
		},
		'50638350': {
			version: 'V2025.9.9',
			file: 'V2025.9.9/offsets.json',
			offsetsVersion: 8,
		},
		'50641800': {
			version: 'V17.0.1s',
			file: 'V2025.9.9/offsets.json',
			offsetsVersion: 8,
		},
		'50643450': {
			version: 'V17.1.0s',
			file: 'V2025.9.9/offsets.json',
			offsetsVersion: 8,
		},
		'50656300': {
			version: 'V17.4.0',
			file: 'V17.4.0/offsets.json',
			offsetsVersion: 5,
		},
		'50663350': {
			version: 'V2026.8.18',
			file: 'V2026.8.18/offsets.json',
			offsetsVersion: 5,
		},
		default: {
			version: 'V2026.8.18',
			file: 'V2026.8.18/offsets.json',
			offsetsVersion: 5,
		},
	},
} as unknown as IOffsetsLookup;

export const EMBEDDED_OFFSETS: { x64: IOffsets; x86: IOffsets } = {
	x64: {
		meetingHud: [-1, 184, 0],
		objectCachePtr: [16],
		meetingHudState: [224],
		allPlayersPtr: [-1, 184, 0, 32],
		allPlayers: [16],
		playerCount: [24],
		playerAddrPtr: 32,
		shipStatus: [-1, 184, 0],
		shipStatus_systems: [248],
		shipStatus_map: [428],
		shipstatus_allDoors: [224],
		door_doorId: 32,
		door_isOpen: 40,
		deconDoorUpperOpen: [32, 40],
		deconDoorLowerOpen: [40, 40],
		hqHudSystemType_CompletedConsoles: [24, 32],
		HudOverrideSystemType_isActive: [16],
		miniGame: [-1, 184, 0],
		planetSurveillanceMinigame_currentCamera: [256],
		planetSurveillanceMinigame_camarasCount: [216, 24],
		surveillanceMinigame_FilteredRoomsCount: [168, 24],
		lightRadius: [200, 32],
		palette: [-1, 184],
		palette_playercolor: [648],
		palette_shadowColor: [656],
		playerControl_GameOptions: [-1, 184, 4],
		gameoptionsData: [-1, 184, 0, 40],
		gameOptions_MapId: [28],
		gameOptions_MaxPLayers: [20],
		serverManager_currentServer: [-1, 184, 8, 16, 8],
		connectFunc: 4095,
		showModStampFunc: 4095,
		modLateUpdateFunc: 255,
		fixedUpdateFunc: 4095,
		pingMessageString: 4095,
		innerNetClient: {
			base: [-1, 184, 0],
			networkAddress: 40,
			networkPort: 48,
			gameMode: 68,
			gameId: 72,
			hostId: 76,
			clientId: 80,
			gameState: 172,
			onlineScene: 288,
			mainMenuScene: 296,
		},
		player: {
			struct: [
				{
					type: 'SKIP',
					skip: 56,
					name: 'unused',
				},
				{
					type: 'UINT',
					name: 'id',
				},
				{
					type: 'SKIP',
					skip: 28,
					name: 'unused',
				},
				{
					type: 'UINT',
					name: 'outfitsPtr',
				},
				{
					type: 'SKIP',
					skip: 4,
					name: 'unused',
				},
				{
					type: 'UINT',
					name: 'playerLevel',
				},
				{
					type: 'UINT',
					name: 'disconnected',
				},
				{
					type: 'UINT',
					name: 'rolePtr',
				},
				{
					type: 'SKIP',
					skip: 4,
					name: 'unused',
				},
				{
					type: 'UINT',
					name: 'taskPtr',
				},
				{
					type: 'SKIP',
					skip: 4,
					name: 'unused',
				},
				{
					type: 'BYTE',
					name: 'dead',
				},
				{
					type: 'SKIP',
					skip: 7,
					name: 'unused',
				},
				{
					type: 'UINT',
					name: 'objectPtr',
				},
				{
					type: 'SKIP',
					skip: 4,
					name: 'unused',
				},
			],
			isDummy: [280],
			isLocal: [88, 220],
			localX: [224, 64, 16, 176],
			localY: [224, 64, 16, 180],
			remoteX: [224, 64, 16, 176],
			remoteY: [224, 64, 16, 180],
			bufferLength: 136,
			offsets: [0, 0],
			inVent: [104],
			clientId: [48],
			currentOutfit: [100],
			roleTeam: [116],
			nameText: [88, 96, 224],
			outfit: {
				colorId: [16],
				hatId: [24],
				skinId: [40],
				visorId: [48],
				playerName: [64],
			},
		},
		signatures: {
			innerNetClient: {
				sig: '8B 0D ? ? ? ? 48 8B E8 48 8B 91 B8 00 00 00 48 8B 0A',
				patternOffset: 2,
				addressOffset: 4,
			},
			meetingHud: {
				sig: '8B 05 ? ? ? ? 48 8B 7B 50 48 8B 88 B8 00 00 00',
				patternOffset: 2,
				addressOffset: 4,
			},
			gameData: {
				sig: '8B 0D ? ? ? ? 48 8B D8 48 8B 91 B8 00 00 00 48 8B 0A 48 85 C9 74 ?',
				patternOffset: 2,
				addressOffset: 4,
			},
			shipStatus: {
				sig: '8B 05 ? ? ? ? 49 8B 7E 28',
				patternOffset: 2,
				addressOffset: 4,
			},
			miniGame: {
				sig: '8B 05 ? ? ? ? 48 8B 88 B8 00 00 00 48 8B 09 48 85 C9 74 ? 33 D2 E8 ? ? ? ? 85 C0',
				patternOffset: 2,
				addressOffset: 4,
			},
			palette: {
				sig: '8B 05 ? ? ? ? 7C ?',
				patternOffset: 2,
				addressOffset: 4,
			},
			playerControl: {
				sig: '8B 05 ? ? ? ? 48 8B 80 B8 00 00 00 48 89 74 24 50 48 89 7C 24 58',
				patternOffset: 2,
				addressOffset: 4,
			},
			showModStamp: {},
			connectFunc: {},
			fixedUpdateFunc: {},
			pingMessageString: {},
			modLateUpdate: {},
			serverManager: {
				sig: '8B 05 ? ? ? ? 48 8B 80 B8 00 00 00 45 33 C0 48 8B 10 48 8D 4C 24 30',
				patternOffset: 2,
				addressOffset: 4,
			},
			gameOptionsManager: {
				sig: '8B 05 ? ? ? ? 48 8B 88 B8 00 00 00 48 8B 01 48 85 C0 74 ? 4C 8B 40 40',
				patternOffset: 2,
				addressOffset: 4,
			},
		},
		oldMeetingHud: false,
		disableWriting: false,
		newGameOptions: true,
	} as unknown as IOffsets,
	x86: {
		meetingHud: [-1, 92, 0],
		objectCachePtr: [8],
		meetingHudState: [136],
		allPlayersPtr: [-1, 92, 0, 16],
		allPlayers: [8],
		playerCount: [12],
		playerAddrPtr: 16,
		shipStatus: [-1, 92, 0],
		shipStatus_systems: [160],
		shipStatus_map: [256],
		shipstatus_allDoors: [148],
		door_doorId: 16,
		door_isOpen: 24,
		deconDoorUpperOpen: [16, 24],
		deconDoorLowerOpen: [20, 24],
		hqHudSystemType_CompletedConsoles: [12, 16],
		HudOverrideSystemType_isActive: [8],
		miniGame: [-1, 92, 0],
		planetSurveillanceMinigame_currentCamera: [136],
		planetSurveillanceMinigame_camarasCount: [116, 12],
		surveillanceMinigame_FilteredRoomsCount: [92, 12],
		lightRadius: [140, 16],
		palette: [-1, 92],
		palette_playercolor: [644],
		palette_shadowColor: [648],
		playerControl_GameOptions: [-1, 92, 20],
		gameoptionsData: [-1, 92, 0, 20],
		gameOptions_MapId: [20],
		gameOptions_MaxPLayers: [12],
		serverManager_currentServer: [-1, 92, 4, 20, 8],
		connectFunc: 4095,
		showModStampFunc: 4095,
		modLateUpdateFunc: 255,
		fixedUpdateFunc: 4095,
		pingMessageString: 4095,
		innerNetClient: {
			base: [-1, 92, 0],
			networkAddress: 20,
			networkPort: 24,
			gameMode: 40,
			gameId: 44,
			hostId: 48,
			clientId: 52,
			gameState: 100,
			onlineScene: 176,
			mainMenuScene: 180,
		},
		player: {
			struct: [
				{
					type: 'SKIP',
					skip: 40,
					name: 'unused',
				},
				{
					type: 'UINT',
					name: 'id',
				},
				{
					type: 'SKIP',
					skip: 20,
					name: 'unused',
				},
				{
					type: 'UINT',
					name: 'outfitsPtr',
				},
				{
					type: 'UINT',
					name: 'playerLevel',
				},
				{
					type: 'UINT',
					name: 'disconnected',
				},
				{
					type: 'UINT',
					name: 'rolePtr',
				},
				{
					type: 'UINT',
					name: 'taskPtr',
				},
				{
					type: 'BYTE',
					name: 'dead',
				},
				{
					type: 'SKIP',
					skip: 3,
					name: 'unused',
				},
				{
					type: 'UINT',
					name: 'objectPtr',
				},
			],
			isDummy: [184],
			isLocal: [60, 132],
			localX: [152, 44, 8, 124],
			localY: [152, 44, 8, 128],
			remoteX: [152, 44, 8, 124],
			remoteY: [152, 44, 8, 128],
			bufferLength: 92,
			offsets: [0, 0],
			inVent: [72],
			clientId: [32],
			currentOutfit: [68],
			roleTeam: [80],
			nameText: [60, 52, 132],
			outfit: {
				colorId: [8],
				hatId: [12],
				skinId: [20],
				visorId: [24],
				playerName: [32],
			},
		},
		signatures: {
			innerNetClient: {
				sig: 'A1 ? ? ? ? 8B 40 5C 8B 00 85 C0 74 ? 6A 00 FF 75 F4',
				patternOffset: 1,
				addressOffset: 0,
			},
			meetingHud: {
				sig: 'A1 ? ? ? ? 8B 40 5C 8B 00 89 45 E4 A1 ? ? ? ?',
				patternOffset: 1,
				addressOffset: 0,
			},
			gameData: {
				sig: '8B 0D ? ? ? ? 8B F0 83 C4 04 8B 49 5C',
				patternOffset: 2,
				addressOffset: 0,
			},
			shipStatus: {
				sig: 'A1 ? ? ? ? 6A 00 FF 75 08 8B 40 5C 8B 38',
				patternOffset: 1,
				addressOffset: 0,
			},
			miniGame: {
				sig: 'A1 ? ? ? ? C7 45 FC 00 00 00 00 8B 40 5C 8B 10',
				patternOffset: 1,
				addressOffset: 0,
			},
			palette: {
				sig: 'A1 ? ? ? ? 83 C4 04 8B 40 5C 0F 10 40 30',
				patternOffset: 1,
				addressOffset: 0,
			},
			playerControl: {
				sig: 'A1 ? ? ? ? 83 C4 04 8B 40 5C 8B 38 A1 ? ? ? ? 8B 40 5C',
				patternOffset: 1,
				addressOffset: 0,
			},
			showModStamp: {
				sig: '55 8B EC 8B 45 08 8B 40 10 85 C0 74 0F 6A 00 6A 01 50 E8 ? ? ? ? 83 C4 0C 5D C3 E9 ? ? ? ?',
				patternOffset: 0,
				addressOffset: -5,
			},
			connectFunc: {
				sig: 'E8 ? ? ? ? A1 ? ? ? ? 83 C4 0C 8B 40 5C 8B 00 85 C0 0F 84 ? ? ? ? 6A 00 50 E8 ? ? ? ? 89',
				patternOffset: 1,
				addressOffset: 4,
			},
			fixedUpdateFunc: {
				sig: '75 ? 8B 46 ? 85 C0 74 0B 6A 00 50 E8 ? ? ? ? 83 C4 08 83 7E ? 00',
				patternOffset: 0,
				addressOffset: -5,
			},
			pingMessageString: {
				sig: 'E8 ? ? ? ? 6A 00 50 FF 35 ? ? ? ? E8 ? ? ? ? 83 C4 1C 8B C8 85 F6 74 1A 8B 06 FF B0 ? ? ? ? 8B',
				patternOffset: 10,
				addressOffset: 0,
			},
			modLateUpdate: {
				sig: '53 8B DC 83 EC 08 83 E4 F0 83 C4 04 55 8B 6B 04 89 6C 24 04 8B EC 83 EC 28 80 3D',
				patternOffset: 0,
				addressOffset: 0,
			},
			serverManager: {
				sig: 'A1 ? ? ? ? 83 C4 04 8B 40 5C 6A 00 FF 30 8D 45 DC',
				patternOffset: 1,
				addressOffset: 0,
			},
			gameOptionsManager: {
				sig: 'A1 ? ? ? ? 57 8B 40 5C 8B 38 85 FF 74 ?',
				patternOffset: 1,
				addressOffset: 0,
			},
		},
		oldMeetingHud: false,
		disableWriting: true,
		newGameOptions: true,
	} as unknown as IOffsets,
};
