#!/usr/bin/env node
// Regenerates src/main/embeddedOffsets.ts — the bundle the client falls back to when the
// mirror cannot be reached.
//
//     node scripts/embed-offsets.mjs            # from the live mirror
//     node scripts/embed-offsets.mjs --fixtures # from test/fixtures/offsets, offline
//
// It embeds the lookup and the two offsets files the lookup's `default` entry names, one
// per architecture. Not the whole tree: the floor exists so that a player whose mirror is
// unreachable can still start and play the *current* game build, and carrying eighty
// historical files to serve a player who is running a two-year-old Among Us would trade a
// megabyte of installer for a case that does not happen.
//
// Run it whenever the mirror's default version changes, and commit the result.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const fromFixtures = process.argv.includes('--fixtures');
const MIRROR = 'https://raw.githubusercontent.com/greluc/AnotherCrewlink-Offsets/main';

async function read(path) {
	if (fromFixtures) {
		// The fixtures are the same tree with the separators flattened.
		const flat = path.replaceAll('/', '__');
		const candidates = readdirSync(join(root, 'test/fixtures/offsets'));
		const match = candidates.find((name) => name === flat);
		if (!match) throw new Error(`no fixture for ${path} (looked for ${flat})`);
		return JSON.parse(readFileSync(join(root, 'test/fixtures/offsets', match), 'utf8'));
	}
	const response = await fetch(`${MIRROR}/${path}`, { signal: AbortSignal.timeout(30000) });
	if (!response.ok) throw new Error(`${path} responded with HTTP ${response.status}`);
	return response.json();
}

const lookup = await read('lookup.json');
const fallback = lookup.versions?.default;
if (!fallback?.file) {
	throw new Error('the lookup has no default entry, so there is nothing to embed');
}

const offsets = {};
for (const arch of ['x64', 'x86']) {
	offsets[arch] = await read(`offsets/${arch}/${fallback.file}`);
}

const source = `// GENERATED by scripts/embed-offsets.mjs — do not edit by hand.
//
// The floor. When the mirror is unreachable — DNS failure, a 404, an empty cache — the
// client reads this instead of refusing to start, and says so rather than falling back
// silently. It is validated on load like any other bundle, because a build that shipped a
// malformed floor should fail its own tests rather than its users.
//
// Game build: ${fallback.version}
// Source file: ${fallback.file}
// Regenerate with: node scripts/embed-offsets.mjs

import type { IOffsets, IOffsetsLookup } from './offsetStore';

/** The build this floor describes, for the message the client shows when it is in use. */
export const EMBEDDED_GAME_VERSION = ${JSON.stringify(fallback.version)};

/** The offsets file the embedded lookup's default entry names. */
export const EMBEDDED_OFFSETS_FILE = ${JSON.stringify(fallback.file)};

export const EMBEDDED_LOOKUP: IOffsetsLookup = ${JSON.stringify(lookup, null, '\t')} as unknown as IOffsetsLookup;

export const EMBEDDED_OFFSETS: { x64: IOffsets; x86: IOffsets } = {
\tx64: ${JSON.stringify(offsets.x64, null, '\t').replaceAll('\n', '\n\t')} as unknown as IOffsets,
\tx86: ${JSON.stringify(offsets.x86, null, '\t').replaceAll('\n', '\n\t')} as unknown as IOffsets,
};
`;

const target = join(root, 'src/main/embeddedOffsets.ts');
writeFileSync(target, source, 'utf8');
console.log(
	`embedded ${fallback.version} (${fallback.file}) from ${fromFixtures ? 'fixtures' : 'the mirror'} — ${
		Math.round(source.length / 1024)
	} KB`
);
